name: FlaskApplication
on: 
    push:
        branches: 
            - main
jobs:
    testing:
        runs-on: ubuntu-latest

        steps:
        
            - name: checkout
              uses: actions/checkout@v4
        
            - name: list all the files
              run: ls -al
            
            - name: install pip
              run: sudo apt install pip -y

            - name: lets install all the dependencies
              run: pip install -r requirements.txt