name: FlaskApplication
on: 
    push:
        branches: 
            - main
jobs:
    testing:
        runs-on: ubuntu-latest

        steps:
        
            - name: checkout
              uses: actions/checkout@v4
        
            - name: list all the files
              run: ls -al
            
            - name: install pip
              run: sudo apt install awscli pip -y

            - name: lets install all the dependencies
              run: pip install -r requirements.txt

            - name: aws configuration
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ap-south-1

            - name: testing aws
              run: aws ec2 describe-instances