name: FlaskApplication
on: 
    push:
        branches: 
            - main
jobs:
    runs-on: 'ubuntu-latest'

    steps:
        
        - name: checkout
          uses: actions/checkout@v4
        
        - name: list all the files
          run: ls -al